
name: Setup Hugo

on: 
  push:
    branches:
      - main

jobs:
  setup-hugo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Configure Git user
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Clone and extract example site
      run: |
        # Create a temporary directory
        TEMP_DIR=$(mktemp -d)
        # Clone the theme repository
        git clone https://github.com/monkeyWzr/hugo-theme-cactus $TEMP_DIR
        # Check for exampleSite directory and copy its contents if it exists
        if [ -d "$TEMP_DIR/exampleSite" ]; then
          cp -r $TEMP_DIR/exampleSite/* .
          cp -r $TEMP_DIR/exampleSite/.* . 2>/dev/null || true
        fi
        # Clean up
        rm -rf $TEMP_DIR

    - name: Check theme installation
      id: theme_check
      run: |
        # Check for theme in themes directory
        if [ -d "themes/hugo-theme-cactus" ]; then
          echo "theme_exists=true" >> $GITHUB_OUTPUT
        # Check for theme in go.mod
        elif [ -f "go.mod" ] && grep -q "hugo-theme-cactus" go.mod; then
          echo "theme_exists=true" >> $GITHUB_OUTPUT
        else
          echo "theme_exists=false" >> $GITHUB_OUTPUT
        fi

    - name: Install theme if needed
      if: steps.theme_check.outputs.theme_exists == 'false'
      run: |
        # Create themes directory if it doesn't exist
        mkdir -p themes
        # Add theme as submodule
        git submodule add https://github.com/monkeyWzr/hugo-theme-cactus themes/hugo-theme-cactus
        # Update theme parameter in config file
        for config in config.toml config.yaml config.yml; do
          if [ -f "$config" ]; then
            if [[ "$config" == *.toml ]]; then
              sed -i 's|^theme *= *.*|theme = "hugo-theme-cactus"|' "$config"
            elif [[ "$config" == *.yaml ]] || [[ "$config" == *.yml ]]; then
              sed -i 's|^theme:.*|theme: "hugo-theme-cactus"|' "$config"
            fi
            break
          fi
        done

    - name: Delete Workflow File
      run: |
        rm .github/workflows/hugo-setup.yml

    - name: Commit and push changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git add .
        git commit -m "Initial setup with hugo-theme-cactus theme"
        git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/hugotion/${{ github.event.repository.name }}.git main

    - name: Workflow Webhook Action
      uses: distributhor/workflow-webhook@v3
      with:
        webhook_url: 'https://cool-pelican-27.convex.site/callbackPageDeployed'
        webhook_auth_type: "bearer"
        webhook_auth: ${{ secrets.CALLBACK_BEARER }}
        data: '{ "workflowRunning": false }'
